[package]
name = "tpt-rift-transport-ws"
description = "WebSocket transport for tpt-rift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-rift = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.24"
